// Codegen for the in-app handoff exports. Reads each prototype's source files
// VERBATIM from disk and embeds them (as escaped string literals) into a
// handoff/sources.generated.ts, which that prototype's in-app "Download .zip"
// button bundles. Run via the app's dev/build scripts.
//
// We read from disk (rather than a bundler `?raw` import) so the engineer gets
// the original TypeScript — types, comments, formatting — not transpiled JS.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// cwd is the app dir (apps/scaleui3) when run via pnpm.
const root = process.cwd();

// One entry per prototype. `files` is [ on-disk path, path inside the zip ].
const BUNDLES = [
  {
    label: 'Falcon',
    target: 'src/components/falcon/handoff/sources.generated.ts',
    files: [
      ['src/components/falcon/HANDOFF.md', 'HANDOFF.md'],
      ['src/app/falcon/page.tsx', 'src/app/falcon/page.tsx'],
      ['src/components/falcon/types.ts', 'src/components/falcon/types.ts'],
      ['src/components/falcon/lib.tsx', 'src/components/falcon/lib.tsx'],
      ['src/components/falcon/nav-shell.tsx', 'src/components/falcon/nav-shell.tsx'],
      ['src/components/falcon/customer-catalog.tsx', 'src/components/falcon/customer-catalog.tsx'],
      ['src/components/falcon/customer-detail.tsx', 'src/components/falcon/customer-detail.tsx'],
      ['src/components/falcon/fi-browse.tsx', 'src/components/falcon/fi-browse.tsx'],
      ['src/components/falcon/workspace-detail.tsx', 'src/components/falcon/workspace-detail.tsx'],
      ['src/components/falcon/states.tsx', 'src/components/falcon/states.tsx'],
      ['src/components/falcon/data/fixtures.ts', 'src/components/falcon/data/fixtures.ts'],
      ['src/components/falcon/data/source.ts', 'src/components/falcon/data/source.ts'],
      ['src/components/falcon/data/util.ts', 'src/components/falcon/data/util.ts'],
      ['src/components/falcon/data/index.ts', 'src/components/falcon/data/index.ts'],
    ],
  },
  {
    label: 'Golden Agent',
    target: 'src/components/agentex-cicd/handoff/sources.generated.ts',
    files: [
      ['src/components/agentex-cicd/HANDOFF.md', 'HANDOFF.md'],
      ['src/app/golden-agent/page.tsx', 'src/app/golden-agent/page.tsx'],
      ['src/components/agentex-cicd/agentex-cicd.tsx', 'src/components/agentex-cicd/agentex-cicd.tsx'],
      ['src/components/agentex-cicd/customizable-agents.tsx', 'src/components/agentex-cicd/customizable-agents.tsx'],
      ['src/components/sgp-nav/sgp-nav.tsx', 'src/components/sgp-nav/sgp-nav.tsx'],
    ],
  },
];

for (const bundle of BUNDLES) {
  const entries = bundle.files.map(([disk, zipPath]) => {
    const content = readFileSync(join(root, disk), 'utf8');
    return `  { path: ${JSON.stringify(zipPath)}, content: ${JSON.stringify(content)} },`;
  }).join('\n');

  const out = `// AUTO-GENERATED by scripts/gen-handoff.mjs — do not edit by hand.
// Verbatim ${bundle.label} prototype source, embedded for the in-app handoff .zip export.
export interface HandoffFile { path: string; content: string }
export const HANDOFF_FILES: HandoffFile[] = [
${entries}
];
`;

  const target = join(root, bundle.target);
  writeFileSync(target, out, 'utf8');
  console.log(`gen-handoff: wrote ${bundle.files.length} files → ${target}`);
}
